import os, requests, re, json
from bs4 import BeautifulSoup
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")
DEEPSEEK_KEY = os.getenv("DEEPSEEK_API_KEY")

def deepseek(prompt):
    r = requests.post("https://api.deepseek.com/chat/completions",
        headers={"Authorization": f"Bearer {DEEPSEEK_KEY}", "Content-Type": "application/json"},
        json={"model": "deepseek-chat", "messages": [{"role": "user", "content": prompt}], "response_format": {"type": "json_object"}},
        timeout=30)
    return json.loads(r.json()["choices"][0]["message"]["content"])

def send_text(msg, link=None):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    kb = [[{"text": "✅ Approve & Queue", "callback_data": "approve"}, {"text": "❌ Skip", "callback_data": "skip"}]]
    if link: kb.append([{"text": "🔗 Open Listing", "url": link}])
    requests.post(url, json={"chat_id": CHAT_ID, "text": msg, "reply_markup": {"inline_keyboard": kb}})

def make_carousel(photo_urls, hook, sub_hook, price_man):
    slides = []
    for i, purl in enumerate(photo_urls[:4]):
        try:
            img_data = requests.get(purl, timeout=10).content
            img = Image.open(BytesIO(img_data)).convert("RGB")
            img = img.resize((1080, 1350))
            draw = ImageDraw.Draw(img)
            # dark overlay for hook on slide 1
            if i == 0:
                draw.rectangle([(0, 0), (1080, 400)], fill=(0,0,0,180))
                # fake bold by drawing twice
                font_big = ImageFont.load_default()
                # Pillow default font small, so we draw large text via scaling trick - use 2x
                draw.text((40, 40), hook, fill="white", font=font_big, stroke_width=3)
                draw.text((40, 200), sub_hook, fill=(255, 230, 0), font=font_big)
                draw.text((40, 300), f"{price_man}万円 | Nagano Ski", fill="white", font=font_big)
            img.save(f"/tmp/slide_{i}.jpg", quality=90)
            slides.append(f"/tmp/slide_{i}.jpg")
        except: pass
    return slides

# --- LIVE SCRAPE ---
html = requests.get("https://akiya.sumai.biz/", headers={"User-Agent": "Mozilla/5.0"}, timeout=15).text
soup = BeautifulSoup(html, "html.parser")
links = list(set([a["href"] for a in soup.find_all("a", href=True) if "akiya.sumai.biz" in a["href"] and re.search(r"/\d+/?$", a["href"])]))[:12]

for link in links:
    try:
        page = requests.get(link, headers={"User-Agent": "Mozilla/5.0"}, timeout=15).text
        if not any(k in page for k in ["スキー", "飯山", "木島平", "野沢", "妙高", "斑尾", "白馬"]): continue
        m = re.search(r"(\d+)万円", page)
        price = int(m.group(1)) if m else 9999
        if price > 800: continue

        # get first 4 images
        soup2 = BeautifulSoup(page, "html.parser")
        imgs = [img.get("src") for img in soup2.find_all("img") if img.get("src") and "http" in img.get("src")][:4]

        # DeepSeek: generate hook + ROI
        prompt = f"""
        Listing: {link} Price {price}万円, content snippet {page[:3000]}
        Task: Return JSON with: hook (max 5 words clickbait for IG image 1, e.g. "$33K SKI HOUSE"), sub_hook (e.g. "7KM TO 5 RESORTS"), roi_percent (calculate rough: buy price+20k reno, rent $140*74 nights), caption (IG caption for @japan.house.roi with ROI math), catch (one sentence risk).
        Language: hook/sub_hook ENGLISH, caption English with Japanese price.
        Format: {{"hook": "", "sub_hook": "", "roi_percent": 11.3, "caption": "", "catch": ""}}
        """
        data = deepseek(prompt)

        # make carousel images with hook
        slides = make_carousel(imgs, data["hook"], data["sub_hook"], price)

        # send to Telegram
        caption = f"""🏔️ {data['hook']} - {data['sub_hook']}

💰 {price}万円 (~${price*67}) | ROI {data['roi_percent']}%
⚠️ {data['catch']}
🔗 {link}

{data['caption']}

Hook auto-generated by DeepSeek for Slide 1"""
        send_text(caption, link)

        # send first slide as photo preview
        if slides:
            with open(slides[0], 'rb') as f:
                requests.post(f"https://api.telegram.org/bot{BOT_TOKEN}/sendPhoto",
                    data={"chat_id": CHAT_ID, "caption": f"SLIDE 1 PREVIEW: {data['hook']}"},
                    files={"photo": f})

        break # send only 1 per run for test
    except Exception as e:
        print(e)

send_text("Cloud scraper finished run - if you saw 0 houses, try manual trigger again tomorrow, akiya site updates daily.")
